import {Component,OnInit} from '@angular/core'; import {CommonModule} from '@angular/common'; import {ActivatedRoute,Router,RouterLink} from '@angular/router'; import {ApiService} from '../../core/api.service'; import {Employee} from '../../core/models';
@Component({standalone:true,imports:[CommonModule,RouterLink],template:`
<div class="container narrow"><div *ngIf="!employee" class="card">Loading employee…</div><ng-container *ngIf="employee as e"><div class="page-title"><div><h1>{{e.firstName}} {{e.lastName}}</h1><div class="muted">{{e.employeeCode}} · {{e.jobTitle}}</div></div><div class="buttons"><a class="btn btn-secondary" routerLink="/employees">Back</a><a class="btn btn-primary" [routerLink]="['/employees',e.id,'edit']">Edit</a></div></div>
<div class="card"><div class="metrics"><div><span>Base salary</span><strong>{{money(e.baseSalary,e.currency)}}</strong></div><div><span>Bonus</span><strong>{{money(e.bonus,e.currency)}}</strong></div><div><span>Total compensation</span><strong>{{money(e.totalCompensation,e.currency)}}</strong></div></div>
<div class="details"><div><span>Email</span><b>{{e.email}}</b></div><div><span>Department</span><b>{{e.department}}</b></div><div><span>Country</span><b>{{e.country}}</b></div><div><span>Currency</span><b>{{e.currency}}</b></div><div><span>Joining date</span><b>{{e.joiningDate|date}}</b></div></div>
<div class="danger"><button class="btn btn-danger" (click)="remove(e)">Delete employee</button></div></div></ng-container></div>`,
styles:[`.narrow{max-width:900px}.buttons{display:flex;gap:8px}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.metrics div{background:#f8faff;border-radius:12px;padding:16px}.metrics span,.details span{display:block;color:#667085;font-size:12px;margin-bottom:5px}.metrics strong{font-size:21px}.details{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:25px}.danger{border-top:1px solid #edf0f4;margin-top:28px;padding-top:20px}@media(max-width:700px){.metrics,.details{grid-template-columns:1fr}}`]})
export class EmployeeDetailsComponent implements OnInit{employee?:Employee;constructor(private api:ApiService,private route:ActivatedRoute,private router:Router){}ngOnInit(){this.api.employee(Number(this.route.snapshot.paramMap.get('id'))).subscribe(e=>this.employee=e)}
remove(e:Employee){if(confirm(`Delete ${e.firstName} ${e.lastName}?`))this.api.deleteEmployee(e.id).subscribe(()=>this.router.navigate(['/employees']))}
money(v:number,c:string){return new Intl.NumberFormat(undefined,{style:'currency',currency:c,maximumFractionDigits:0}).format(v)}}
