import {Component,OnInit} from '@angular/core'; import {CommonModule} from '@angular/common'; import {FormBuilder,ReactiveFormsModule,Validators} from '@angular/forms'; import {ActivatedRoute,Router,RouterLink} from '@angular/router'; import {forkJoin} from 'rxjs'; import {ApiService} from '../../core/api.service'; import {EmployeeRequest} from '../../core/models';
@Component({standalone:true,imports:[CommonModule,ReactiveFormsModule,RouterLink],template:`
<div class="container narrow"><div class="page-title"><div><h1>{{id?'Edit employee':'Add employee'}}</h1><div class="muted">Maintain compensation information</div></div><a class="btn btn-secondary" routerLink="/employees">Cancel</a></div>
<form class="card" [formGroup]="form" (ngSubmit)="save()"><div class="grid">
<label><span class="label">Employee code</span><input class="input" formControlName="employeeCode"></label><label><span class="label">Email</span><input class="input" type="email" formControlName="email"></label>
<label><span class="label">First name</span><input class="input" formControlName="firstName"></label><label><span class="label">Last name</span><input class="input" formControlName="lastName"></label>
<label><span class="label">Department</span><input class="input" formControlName="department" list="departments"></label><label><span class="label">Job title</span><input class="input" formControlName="jobTitle"></label>
<label><span class="label">Country</span><input class="input" formControlName="country" list="countries"></label><label><span class="label">Currency (ISO)</span><input class="input" maxlength="3" formControlName="currency"></label>
<label><span class="label">Base salary</span><input class="input" type="number" min="0" step=".01" formControlName="baseSalary"></label><label><span class="label">Bonus</span><input class="input" type="number" min="0" step=".01" formControlName="bonus"></label>
<label><span class="label">Joining date</span><input class="input" type="date" formControlName="joiningDate"></label></div>
<datalist id="departments"><option *ngFor="let x of departments" [value]="x"></option></datalist><datalist id="countries"><option *ngFor="let x of countries" [value]="x"></option></datalist>
<div class="error" *ngIf="form.invalid&&submitted">Please complete all fields with valid values.</div><div class="error" *ngIf="serverError">{{serverError}}</div>
<div class="footer"><button class="btn btn-primary" type="submit" [disabled]="saving">{{saving?'Saving…':'Save employee'}}</button></div></form></div>`,
styles:[`.narrow{max-width:900px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.footer{display:flex;justify-content:flex-end;margin-top:22px}@media(max-width:700px){.grid{grid-template-columns:1fr}}`]})
export class EmployeeFormComponent implements OnInit{id?:number;departments:string[]=[];countries:string[]=[];saving=false;submitted=false;serverError='';
form=this.fb.nonNullable.group({employeeCode:['',[Validators.required,Validators.maxLength(30)]],firstName:['',Validators.required],lastName:['',Validators.required],email:['',[Validators.required,Validators.email]],department:['',Validators.required],jobTitle:['',Validators.required],country:['',Validators.required],currency:['',[Validators.required,Validators.pattern(/^[A-Za-z]{3}$/)]],baseSalary:[0,[Validators.required,Validators.min(0)]],bonus:[0,[Validators.required,Validators.min(0)]],joiningDate:['',Validators.required]});
constructor(private fb:FormBuilder,private api:ApiService,private route:ActivatedRoute,private router:Router){}
ngOnInit(){forkJoin({d:this.api.departments(),c:this.api.countries()}).subscribe(x=>{this.departments=x.d;this.countries=x.c});let v=this.route.snapshot.paramMap.get('id');if(v){this.id=Number(v);this.api.employee(this.id).subscribe(e=>this.form.patchValue({employeeCode:e.employeeCode,firstName:e.firstName,lastName:e.lastName,email:e.email,department:e.department,jobTitle:e.jobTitle,country:e.country,currency:e.currency,baseSalary:e.baseSalary,bonus:e.bonus,joiningDate:e.joiningDate}))}}
save(){this.submitted=true;if(this.form.invalid)return;this.saving=true;this.serverError='';let raw=this.form.getRawValue();let r:EmployeeRequest={...raw,currency:raw.currency.toUpperCase()};let a=this.id?this.api.updateEmployee(this.id,r):this.api.createEmployee(r);a.subscribe({next:e=>this.router.navigate(['/employees',e.id]),error:e=>{this.serverError=e?.error?.message??'Could not save employee.';this.saving=false}})}}
