import {Component,OnInit} from '@angular/core'; import {CommonModule} from '@angular/common'; import {FormsModule} from '@angular/forms'; import {RouterLink} from '@angular/router'; import {Subject,debounceTime,distinctUntilChanged} from 'rxjs'; import {ApiService} from '../../core/api.service'; import {Employee} from '../../core/models';
@Component({standalone:true,imports:[CommonModule,FormsModule,RouterLink],template:`
<div class="container"><div class="page-title"><div><h1>Employees</h1><div class="muted">{{total|number}} salary records</div></div><a class="btn btn-primary" routerLink="/employees/new">+ Add employee</a></div>
<div class="card"><div class="filters"><input class="input" placeholder="Search name, code, email or role…" [(ngModel)]="search" (ngModelChange)="changed($event)">
<select class="input" [(ngModel)]="department" (change)="reset()"><option value="">All departments</option><option *ngFor="let x of departments">{{x}}</option></select>
<select class="input" [(ngModel)]="country" (change)="reset()"><option value="">All countries</option><option *ngFor="let x of countries">{{x}}</option></select>
<select class="input" [(ngModel)]="sortBy" (change)="reset()"><option value="lastName">Name</option><option value="baseSalary">Base salary</option><option value="department">Department</option><option value="country">Country</option><option value="joiningDate">Joining date</option></select>
<select class="input" [(ngModel)]="direction" (change)="reset()"><option value="asc">Ascending</option><option value="desc">Descending</option></select></div>
<div *ngIf="loading" class="state">Loading employees…</div><div *ngIf="error" class="state error">{{error}}</div>
<div class="table-wrap" *ngIf="!loading&&!error"><table><thead><tr><th>Employee</th><th>Department</th><th>Country</th><th>Base salary</th><th>Total comp.</th><th></th></tr></thead><tbody>
<tr *ngFor="let e of employees"><td><b>{{e.firstName}} {{e.lastName}}</b><div class="muted tiny">{{e.employeeCode}} · {{e.jobTitle}}</div></td><td>{{e.department}}</td><td>{{e.country}}</td><td>{{money(e.baseSalary,e.currency)}}</td><td>{{money(e.totalCompensation,e.currency)}}</td><td class="actions"><a [routerLink]="['/employees',e.id]">View</a><a [routerLink]="['/employees',e.id,'edit']">Edit</a></td></tr>
<tr *ngIf="employees.length===0"><td colspan="6" class="state">No employees match.</td></tr></tbody></table></div>
<div class="pager"><button class="btn btn-secondary" [disabled]="page===0" (click)="prev()">Previous</button><span>Page {{page+1}} of {{totalPages||1}}</span><button class="btn btn-secondary" [disabled]="page+1>=totalPages" (click)="next()">Next</button></div></div></div>`,
styles:[`.filters{display:grid;grid-template-columns:2fr repeat(4,1fr);gap:10px;margin-bottom:12px}.state{padding:30px;text-align:center}.tiny{font-size:12px}.actions{white-space:nowrap}.actions a{color:#1f5eff;font-weight:650;margin-right:12px}.pager{display:flex;align-items:center;justify-content:center;gap:16px;padding-top:16px}button:disabled{opacity:.45}@media(max-width:1000px){.filters{grid-template-columns:1fr 1fr}.filters input{grid-column:1/-1}}`]})
export class EmployeeListComponent implements OnInit{employees:Employee[]=[];departments:string[]=[];countries:string[]=[];search='';department='';country='';sortBy='lastName';direction='asc';page=0;size=20;total=0;totalPages=0;loading=false;error='';private search$=new Subject<string>();
constructor(private api:ApiService){} ngOnInit(){this.api.departments().subscribe(x=>this.departments=x);this.api.countries().subscribe(x=>this.countries=x);this.search$.pipe(debounceTime(350),distinctUntilChanged()).subscribe(()=>this.reset());this.load()}
changed(v:string){this.search$.next(v)} reset(){this.page=0;this.load()} prev(){if(this.page>0){this.page--;this.load()}} next(){if(this.page+1<this.totalPages){this.page++;this.load()}}
load(){this.loading=true;this.error='';this.api.employees({page:this.page,size:this.size,search:this.search,department:this.department,country:this.country,sortBy:this.sortBy,direction:this.direction}).subscribe({next:r=>{this.employees=r.content;this.total=r.totalElements;this.totalPages=r.totalPages;this.loading=false},error:()=>{this.error='Could not load employees.';this.loading=false}})}
money(v:number,c:string){return new Intl.NumberFormat(undefined,{style:'currency',currency:c,maximumFractionDigits:0}).format(v)}}
