import {Component,OnInit} from '@angular/core'; import {CommonModule} from '@angular/common'; import {forkJoin} from 'rxjs'; import {ApiService} from '../../core/api.service'; import {Dashboard,SalaryAggregate} from '../../core/models';
@Component({standalone:true,imports:[CommonModule],template:`
<div class="container"><div class="page-title"><div><h1>Salary overview</h1><div class="muted">Compensation insights across ACME</div></div></div>
<div *ngIf="loading" class="card">Loading dashboard…</div><div *ngIf="error" class="card error">{{error}}</div>
<ng-container *ngIf="!loading&&data"><div class="metrics"><div class="card metric"><span>Total employees</span><strong>{{data.totalEmployees|number}}</strong><small>Managed salary records</small></div>
<div class="card metric" *ngFor="let x of data.currencySummaries"><span>Average salary · {{x.currency}}</span><strong>{{money(x.averageBaseSalary,x.currency)}}</strong><small>{{x.employeeCount|number}} employees</small></div></div>
<div class="grid"><section class="card"><h2>Salary by department</h2><p class="muted">Average base salary, separated by currency.</p><div class="row" *ngFor="let x of depts"><div><b>{{x.label}}</b><small>{{x.employeeCount}} employees · {{x.currency}}</small></div><strong>{{money(x.averageBaseSalary,x.currency)}}</strong></div></section>
<section class="card"><h2>Salary by country</h2><p class="muted">Compensation inside each country/currency.</p><div class="row" *ngFor="let x of countries"><div><b>{{x.label}}</b><small>{{x.employeeCount}} employees · {{x.currency}}</small></div><strong>{{money(x.averageBaseSalary,x.currency)}}</strong></div></section></div></ng-container></div>`,
styles:[`.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px;margin-bottom:18px}.metric span,.metric small,.row small{display:block;color:#667085}.metric strong{display:block;font-size:26px;margin:8px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.row{display:flex;justify-content:space-between;gap:10px;padding:12px 0;border-top:1px solid #edf0f4}.row strong{white-space:nowrap}@media(max-width:900px){.grid{grid-template-columns:1fr}}`]})
export class DashboardComponent implements OnInit{data?:Dashboard;depts:SalaryAggregate[]=[];countries:SalaryAggregate[]=[];loading=true;error='';constructor(private api:ApiService){}
ngOnInit(){forkJoin({s:this.api.summary(),d:this.api.byDepartment(),c:this.api.byCountry()}).subscribe({next:r=>{this.data=r.s;this.depts=r.d.slice(0,16);this.countries=r.c;this.loading=false},error:()=>{this.error='Could not load dashboard. Confirm backend is running on port 8080.';this.loading=false}})}
money(v:number,c:string){return new Intl.NumberFormat(undefined,{style:'currency',currency:c,maximumFractionDigits:0}).format(v)}}
